@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkMjAxMjYzYS1lYjIyLTRmNTEtOTdhMC0yNmY0ZWYzOTU1ZjgiLCJlbWFpbCI6ImJoYW51cHJha2FzaEBnbWFpbC5jb20iLCJpYXQiOjE3NTE4MDI4ODYsImV4cCI6MTc1MTg4OTI4Nn0.lTSbc3OEvalQmXJihTgKpCEXVjDCUryx3loQ9y-kw98
@userId=d201263a-eb22-4f51-97a0-26f4ef3955f8
@bookingId=815aacaa-881f-4671-a379-e440df4dc3c5
### POST: Add booking by rider
POST http://localhost:3001/api/booking
Authorization: {{token}}
Content-Type: application/json

{
  "trip_id": "38042afe-7dbd-4a24-9d27-a60f719cf90a",
  "rider_id": "53bdee39-9402-49be-8be8-8f908ec85050",
  "start_geopoint": "0101000020E6100000B58BC9B34FBA5E4055E75D4A0D97F440",
  "end_geopoint": "0101000020E6100000B2C7852EB0CE5140663CE8C94EAE0C40",
  "booked_seats": 1,
  "fare_amount": 80
}

### UPDATE: driver approval
PATCH http://localhost:3001/api/booking/driver-approval/{{bookingId}}
Authorization: {{token}}
Content-Type: application/json

{
  "trip_id": "38042afe-7dbd-4a24-9d27-a60f719cf90a",
  "driver_id": "53bdee39-9402-49be-8be8-8f908ec85050",
  "booking_status": "REJECTED"
}