@id = 74eb3166-1db9-4f58-a494-6b7ca0d05076
@vehicleId = 2eb822fa-71cd-4528-9b78-e4f4570d29ab
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NGViMzE2Ni0xZGI5LTRmNTgtYTQ5NC02YjdjYTBkMDUwNzYiLCJlbWFpbCI6ImphbmUuZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNzUxMzMzOTI4LCJleHAiOjE3NTE0MjAzMjh9.9BVcPw5sIX77G8Sbf66XE7C6iq1fODhCl_i-_SNQa7c
@tripId = 0de6bf67-2703-4026-b4b1-5ac93d4a44e0
### POST - Create a Trip with waypoints
POST http://localhost:3001/api/trip
Authorization: {{token}}
Content-Type: application/json

{
  "vehicle_id": "2eb822fa-71cd-4528-9b78-e4f4570d29ab",
  "driver_id": "74eb3166-1db9-4f58-a494-6b7ca0d05076",
  "start_location_name": "BTM Layout",
  "start_address_line1": "BTM Layout 2nd Stage, Bengaluru, Karnataka 560076",
  "start_geopoint": {"lat": 12.9163, "lng": 77.6105},
  "end_location_name": "EcoSpace Bellandur",
  "end_address_line1": "Outer Ring Rd, Bellandur, Bengaluru, Karnataka 560103",
  "end_geopoint": {"lat": 12.9301, "lng": 77.6783},
  "departure_time": "2025-06-29T09:00:00Z",
  "available_seats": 1,
  "price_per_seat": 90.00,
  "trip_description": "Short morning commute via HSR Layout to EcoSpace ORR.",
  "waypoints": [
    {
      "location_name": "HSR Layout",
      "address_line1": "HSR 27th Main Rd, Bengaluru, Karnataka 560102",
      "geopoint": {"lat": 12.9114, "lng": 77.6412},
      "sequence_order": 1
    }
  ]
}

### GET - Get Trip based on tripId
GET http://localhost:3001/api/trip/{{tripId}}
Authorization: {{token}}

### PUT - Update Trip based on tripId
PUT http://localhost:3001/api/trip/{{tripId}}
Authorization: {{token}}
Content-Type: application/json


{
  "vehicle_id": "2eb822fa-71cd-4528-9b78-e4f4570d29ab",
  "driver_id": "74eb3166-1db9-4f58-a494-6b7ca0d05076",
  "start_location_name": "Rajajinagar 1st Block",
  "start_address_line1": "Dr Rajkumar Rd, Rajajinagar, Bengaluru, Karnataka 560010",
  "start_geopoint": {"lat": 12.9822, "lng": 77.5331},
  "end_location_name": "Electronic City Phase 1",
  "end_address_line1": "Electronic City, Bengaluru, Karnataka 560100",
  "end_geopoint": {"lat": 12.8398, "lng": 77.6770},
  "departure_time": "2025-06-29T13:45:00Z",
  "available_seats": 1,
  "price_per_seat": 250.00,
  "trip_description": "Workday commute from West Bengaluru to E-city, passing BTM and Silk Board.",
  "polyline_path": "optional_encoded_polyline_string",
  "waypoints": [
    {
      "location_name": "BTM Layout",
      "address_line1": "BTM Layout 2nd Stage, Bengaluru, Karnataka 560076",
      "geopoint": {"lat": 12.9156, "lng": 77.6101},
      "sequence_order": 1
    },
    {
      "location_name": "Silk Board Junction",
      "address_line1": "Outer Ring Road, Bengaluru, Karnataka 560068",
      "geopoint": {"lat": 12.9172, "lng": 77.6233},
      "sequence_order": 2
    }
  ]
}

###PATCH - update the status
PATCH http://localhost:3001/api/trip/{{tripId}}/status
Authorization: {{token}}
Content-Type: application/json

{
  "status": "COMPLETED"
}
### GET - get all trips based on filters
GET http://localhost:3001/api/trip?start_lat=12.9114&start_lng=77.6412&end_lat=12.9301&end_lng=77.6783&radius_km=2&trip_status=SCHEDULED
Authorization: {{token}}

### DELETE - Delete Trip
DELETE http://localhost:3001/api/trip/{{tripId}}
Authorization: {{token}}