### POST - Create User
POST http://localhost:3001/api/user/signup
Content-Type: application/json

{
  "email": "bhanuprakash@gmail.com",
  "phone_number": "+919347214120",
  "password": "SecurePass123!",
  "first_name": "Bhanu",
  "last_name": "P",
  "profile_picture": "https://example.com/images/jane.jpg",
  "date_of_birth": "1995-07-15",
  "gender": "MALE",
  "bio": "Passionate traveler and photographer. Coffee enthusiast ☕."
}

### POST - Login User
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
  "email": "bhanuprakash@gmail.com",
  "password": "SecurePass123!"
}

### GET - Get User Details
@id = 74eb3166-1db9-4f58-a494-6b7ca0d05076
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NGViMzE2Ni0xZGI5LTRmNTgtYTQ5NC02YjdjYTBkMDUwNzYiLCJlbWFpbCI6ImphbmUuZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQ5ODM1NjQ3LCJleHAiOjE3NDk5MjIwNDd9.x2otWv7JIyNlQVmQHvvzkbEcNuFcBtQm7lDuI9nP9CI

GET http://localhost:3001/api/user/{{id}}
Authorization: {{token}}
Content-Type: application/json


### POST - Update User Details
PUT http://localhost:3001/api/user/{{id}}
Authorization: {{token}}
Content-Type: application/json

{
  "phone_number": "9347214123"
}

### DELETE - DELETE User
DELETE http://localhost:3001/api/user/{{id}}
Authorization: {{token}}

### PUT - Change Password
PUT http://localhost:3001/api/user/reset-password/{{id}}
Authorization: {{token}}
Content-Type: application/json

{
  "currentPassword": "SecurePass123!",
  "newPassword": "SecurePass321!"
}


### PUT - Update User Preferences
PUT http://localhost:3001/api/user/preferences/{{id}}
Authorization: {{token}}
Content-Type: application/json

{
  "allow_smoking": true,
  "music_genre": ["Rock", "Pop"],
  "has_pets": true,
  "is_pet_friendly": true,
  "communication_preference": "CHATTY",
  "seat_preference": "Window"
}

###GET - Get User Preferences
GET http://localhost:3001/api/user/preferences/{{id}}
Authorization: {{token}}
Content-Type: application/json