### POST - create vehicle
@id = 8488645b-1f93-4c75-84a9-446ef6260f28
@vehicleId = 22bce750-564c-4b4d-adf8-35f8cf46c7ef
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NDg4NjQ1Yi0xZjkzLTRjNzUtODRhOS00NDZlZjYyNjBmMjgiLCJlbWFpbCI6ImphbmUuZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNzQ5NjU3MDkwLCJleHAiOjE3NDk3NDM0OTB9.a1aXpvfcoV-8fXYXCmH5IuiEGkLPDm0zdVQdG5uWCYw

POST http://localhost:3001/api/vehicle
Authorization: {{token}}
Content-Type: application/json

{
  "make": "VolksVegan",
  "model": "Tony",
  "year": 2022,
  "license_plate": "B22343",
  "color": "Silver",
  "seating_capacity": 2,
  "vehicle_ai_image": "image_url"
}


### GET - get vehicled by vehicle id
GET http://localhost:3001/api/vehicle/{{vehicleId}}
Authorization: {{token}}

### GET - get user vehicles
GET http://localhost:3001/api/vehicle/my-vehicles
Authorization: {{token}}

### PUT - update vehicle data
PUT http://localhost:3001/api/vehicle/{{vehicleId}}
Authorization: {{token}}
Content-Type: application/json

{
  "make": "Morris Garage",
  "model": "Breeze",
  "year": 2022,
  "license_plate": "B2C4343"
}

###DELETE - delete vehicle
DELETE http://localhost:3001/api/vehicle/{{vehicleId}}
Authorization: {{token}}
