name: CI/CD for ShareWheels Dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-push-dev-image:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_TAG: dev-${{github.sha}}
      DOCKER_IMAGE_NAME: share_wheels_server
      APP_NODE_ENV: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and Push Docker Image - Dev Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{github.repository_owner}}/${{env.DOCKER_IMAGE_NAME}}:${{env.DOCKER_IMAGE_TAG}}
          build-args: |
            NODE_ENV=${{env.APP_NODE_ENV}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Display Built Image Tag
        run: |
          echo "Yo! Successfully built and pushed image: ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}"